# Generated by Django 3.0.5 on 2020-06-06 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200606_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
