# Generated by Django 3.0.5 on 2020-06-06 12:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
